### ISSUE TITLE
Naming of dataset.py and declaration of transforms

### ISSUE THREAD

**Issue by clegaard** [LukasHedegaard/datasetops#27]
Currently, most of the transforms are implemented in the dataset.py file.
There there is some defined in the compose.py file, related to taking the cartesian product.

It might be reasonable to agree on where transforms should be defined.
What are your thoughts?

**Comment by iliiliiliili** [comment]
I think, current structure is nice – we have operations on single dataset inside the `dataset.py` and transformations on multiple datasets in `compose.py`

**Comment by clegaard** [comment]
As a user (even as a developer) the naming does not make this very clear.
I think that maybe a reasonable distinction, but I don't see why the transforms should be defined in a file called dataset.

**Comment by LukasHedegaard** [comment]
It's not a bad idea to split it up to clarify things. However, we will get a circular import, if we start moving the transforms:
- Most of the free transforms use `_dataset_element_transforming` (e.g. `reshape`)
- `_dataset_element_transforming` in turn return a Dataset
- The dataset transform (`Dataset.reshape`) uses the free transform (`reshape`) in its implementation
= circular.

This is the unfortunate side-effect of having both free and bound versions of the methods available to the user. They both need to be in the dataset.py file.

Moving it then, would then entail a reimplementation to break the circular import, that would otherwise happen.

I recommend, we let it be.

**Comment by LukasHedegaard** [comment]
Do we have a good counter argument? @iliiliiliili @clegaard

**Comment by iliiliiliili** [comment]
> I recommend, we let it be.

I agree
